### PR TITLE
changed --system_alias to --system-alias

### LINKED ISSUE #59: Change --sytem_alias flag
Change `--system_alias` flag to `--system-alias`

### PR DESCRIPTION
**Pull request by Zandew**
Fixes #59 

Check everything which applies

- [x] I have added the issue number for which this pull request is created.

Please reply if I have missed something

### CODE REVIEW

**Comment by Zandew** [comment]
oh ok, I thought I had messed something up, also I should update the readme too

**Comment by Zandew** [comment]
sure I'll do my best

**Comment by arshadkazmi42** [comment]
> oh ok, I thought I had messed something up, also I should update the readme too

Yes. you need to modify the tests and readme.
Just replace all `--system_alias` to `--system-alias`
and it should work fine

**Comment by Zandew** [comment]
alright i think im done

**Pull request merged**
